--includes("common")
--
-----@param strs  string[]
-----@param sep   string
--local function merge_tostring(strs, sep)
--    local s = ""
--    for i = 1, #strs do
--        s = s .. strs[i]
--        if i ~= #strs then s = s .. sep end
--    end
--    return s
--end
--
--rule("csharp")
--do
--    set_extensions(".cs")
--    on_buildcmd_file(
--    ---@param target Target
--    ---@param batch  OperatingSystem
--    ---@param source string
--    ---@param option BuildOptions
--    function (target, batch, source, option)
--        import("lib.detect.find_tool")
--        local csc = find_tool("csc")
--
--        batch:mkdir(target:targetdir())
--
--        local srcs
--        for _, bat in ipairs(target:sourcebatches()) do
--            if bat.rulename == "csharp" then
--                srcs = bat.sourcefiles
--            end
--        end
--        if srcs == nil then print("Could not get files!") return end
--
--        local files = merge_tostring(srcs, ' ')
--
--        print(files)
--    end)
--end
--rule_end()
